### ISSUE TITLE
Fix the imports of the MaterialUI theme

### ISSUE THREAD

**Issue by Manonmani-s** [glaubernespoli/dci-final-project-frontend#10]
https://github.com/creativetimofficial/material-kit-react/issues/66

https://github.com/creativetimofficial/ct-material-dashboard-pro-react/issues/50

https://github.com/creativetimofficial/ct-now-ui-dashboard-pro-react/issues/24

**Comment by glaubernespoli** [comment]
We're not using the MaterialUI Kit React theme as all we need is just the components from the MaterialUI.
