### ISSUE TITLE
Normalizing icons and fixing routes

### ISSUE THREAD

**Issue by glaubernespoli** [glaubernespoli/dci-final-project-frontend#36]
The NavBar and Footer are not using the same icon. They should use the same and the 'Home' Icon should be removed from both components. The application icon should be routed to the Home page.

EXTRA: If easily fixable, also make it that when a route changes, the page scrolls all the way up (instead of staying at the bottom when you click in a link at the footer i.e.).

![image](https://user-images.githubusercontent.com/7003334/109635067-3d3aeb80-7b4a-11eb-8606-c10c1f4ebf1f.png)

![image](https://user-images.githubusercontent.com/7003334/109635094-45932680-7b4a-11eb-954e-f5a8dce58ef2.png)

**Comment by santiagoejm** [comment]
This issue was solve on my previous merge
